import {vehicleTranslations} from './vehicle-language.js?v=2';
import {resolveDealerLocation} from './dealer-context.js?v=13';
// UI-only localization: the same model, configuration and camera stay in place.
const pairs=[
['参考構成','Reference configuration'],
['完成したあなたの一台','Your completed van'],['完成車を見る →','See your van →'],['← 組み合わせを見直す','← Refine your layout'],['あなたの旅を、この一台から。','Your journey starts here.'],['コンタクト','Contact'],['完成車を見る角度','Explore your van'],['ドラッグで回転 · あなたの一台を、いろんな角度から。','Drag to rotate · Explore your van from every angle.'],
['バックドアとスライドドアが開いています','The tailgate and sliding door are open'],['後ろのドアを閉じながら、助手席ドアを開いています','Closing the rear access doors while opening the front passenger door'],['助手席ドアが開いています','The front passenger door is open'],['助手席ドアを閉じています','Closing the front passenger door'],['バックドアを閉じています','Closing the tailgate'],['助手席側のスライドドアを開いています','Opening the passenger-side sliding door'],['スライドドアを閉じています','Closing the sliding door'],['あなたの一台が、走り出します','Your van is ready for the journey'],['完成したレイアウトです。ドラッグで回してご覧ください。','Your layout is ready. Drag to explore.'],['車体を準備しています','Preparing your vehicle'],['完成車を準備しています','Preparing your van'],['保存後の表示を読み込めませんでした。組み合わせは保持しています。','The final preview could not load. Your configuration is still here.'],['画像を保存できませんでした。もう一度お試しください。','The image could not be saved. Please try again.'],
['お問い合わせを閉じる','Close contact'],['あなたが選んだ一台。','The van you created.'],['選んだレイアウトの3Dプレビュー','3D preview of your selected layout'],['組み合わせの内容 ＋','Configuration details +'],['この一台から、相談する。','Let’s talk about your van.'],['過ごし方や、叶えたいことを教えてください。','Tell us how you want to spend your time and what you have in mind.'],['お名前','Your name'],['メールアドレス','Email address'],['ご相談内容','Your message'],['この画面では、今の組み合わせと相談内容の下書きを保存できます。まだ送信されません。','Save a draft with your configuration and message. It will not be sent yet.'],['相談内容を保存','Save enquiry draft'],['コピー','Copy'],['相談内容を下書きとして保存しました。まだ送信されていません。','Enquiry saved as a draft. It has not been sent.'],['相談内容をコピーしました。まだ送信されていません。','Enquiry copied. It has not been sent.'],['コピーできませんでした。「相談内容を保存」をお使いください。','Could not copy. Please use “Save enquiry draft”.'],
['レイアウトスタジオのオープニング','Welcome to the Layout Studio'],['スキップ →','Skip →'],['スタート','Start'],['オープニングを見る ↗','Replay the opening ↗'],['家具のない車体から選ぶ','Start with an empty van'],['準備ができました。スタートからお選びください。','Your van is ready. Select Start to make it yours.'],['3Dを読み込めませんでした。ページを再読み込みしてください。','The 3D view could not load. Please reload the page.'],
['あなたの過ごし方を、この一台に。','A van for the way you live.'],['あなたの過ごし方を、','For the way you live.'],['この一台に。','Make it your own.'],
['Hexa レイアウトスタジオ','Hexa Layout Studio'],['レイアウトスタジオ','Layout Studio'],['レイアウトの選択','Configure your layout'],['言語','Language'],['使い方を閉じる','Close guide'],['使い方','Guide'],
['車体を読み込んでいます','Loading your van'],['選んだ家具・内装を配置しています','Arranging your furniture and finishes'],['車内の3Dレイアウト','3D interior layout'],['選んだ家具と内装を反映したハイエースの3D表示','3D Hiace with your selected furniture and finishes'],['家具から、選んでみましょう。','Start with your furniture.'],['自由に組み合わせる','MAKE IT YOURS'],
['家具','Furniture'],['内装','Finishes'],['設備','Equipment'],['確認','Review'],['内装へ →','Finishes →'],['設備へ →','Equipment →'],['確認へ →','Review →'],['← 戻る','← Back'],['選ぶ項目','Configuration steps'],
['フロント','Front'],['リアのベッド','Rear bed'],['ベッド','Bed'],['サイドキャビネット','Side cabinet'],['家具の素材','Furniture material'],['合板の仕上げ','Plywood finish'],['壁と天井','Walls & ceiling'],['カラーパネル','Colour panels'],['ライト','Lighting'],['エアコン','Air conditioner'],
['プライウッド フロントモジュール','Plywood front module'],['アルミ フロントキッチン','Aluminium front kitchen'],['フロントモジュール','Front module'],['セカンドシート','Second-row seat'],['Iシート','I Seat'],['コの字ベッド','U-shaped lounge bed'],['二の字ベッド','Twin bench bed'],['スライドアウトベッド','Slide-out bed'],['スライドラウンジベッド','Slide lounge bed'],['アルミ スライドベッド','Aluminium slide bed'],['アルミフレーム ベッドモジュール','Aluminium slide bed'],['プライウッド サイドキャビネット','Plywood side cabinet'],['アルミ サイドキャビネット','Aluminium sink cabinet'],['アルミフレーム サイドキャビネット','Aluminium sink cabinet'],['シンプルサイドキャビネット','Simple side cabinet'],['アクティブユース サイドキャビネット','Active side cabinet'],
['セカンドシート、またはフロント設備を。','Keep the second-row seat or add a front module.'],['後部の家具を自由に組み合わせる','Keep seating. Choose your rear furniture.'],['スツール・シンク・冷蔵庫','Stool, sink and fridge'],['ユーロコンテナ・シンク・冷蔵庫','Eurocontainers, sink and fridge'],['コの字に囲まれたラウンジ','A wraparound lounge'],['固定マットレス＋中央5ピース','Fixed cushions + five centre pieces'],['前後2分割・後部コンテナ','Two independent sections + rear containers'],['後部引き出し・室内側の収納','Rear drawer and interior access'],['横へ広げるスライド式','Slides sideways to extend'],['片側スライドベッド','Single-side slide bed'],['両サイドのベッド','Full-width bed'],['片側ベッドは運転席側（右）に配置します。','Single-side beds fit on the driver’s side (right).'],['リアを外して車体を見る','Clear the rear furniture'],['助手席側（左）に、お好みの収納を。','Add storage on the passenger side (left).'],['両サイドの収納を含むため、キャビネットは追加しません。','Storage is already included on both sides. No extra cabinet is needed.'],['フリップアップテーブル','Flip-up table'],['シンク・給排水・シャワー','Sink, water tanks and shower'],['収納・100V／12V出力','Storage and 100V / 12V outlets'],['ENGEL冷蔵庫・シャワー','ENGEL fridge and shower'],['ベッド単体のレイアウト','Bed without a side cabinet'],
['ヘキサ合板','Hexa plywood'],['バーチ合板','Birch plywood'],['家具天板の素材を見る','About the worktop'],['家具の天板素材','Furniture worktop material'],['家具の天板','Furniture worktop'],['アルベロ合板','Albero plywood'],['オーク木目柄のメラミン仕上げ。芯材は白樺合板です。','Oak-grain melamine finish over a birch plywood core.'],['フロントモジュールとサイドキャビネットの天板に採用。ヘキサ・バーチのどちらも共通です。','Used for front-module and side-cabinet worktops, with both Hexa and birch finishes.'],['ベッドの天板は対象外です。','Bed tops are excluded.'],['小口は木の色。機器の色は共通です。','Exposed edges retain their wood colour. Appliance colours stay the same.'],['ALBERO合板の素材見本。オーク木目柄の表面と合板の小口','ALBERO sample showing the oak-grain face and plywood edge'],
['壁・天井なし','Neither'],['壁＋天井','Walls + ceiling'],['壁と天井を付けない','Keep both unfinished'],['リア運転席側 · 100mmピッチ＋カラーパネル','Rear driver’s wall · 100 mm spacing + panels'],['選んだ壁面と突板天井を付ける','Add your chosen walls and veneer ceiling'],['壁の色','Wall colour'],['パネルの色','Panel colour'],['天井の樹種','Ceiling wood'],['本物の木を薄くスライスした、天然木突板の天井です。','Ceiling panels finished with a thin veneer of real wood.'],['壁面を見る','View the wall'],['天井を見上げる','Look up at the ceiling'],['壁は裏側から透過します。','The back of the wall is transparent in this view.'],['天井は透過表示です。「天井を見上げる」で木目と開口を確認できます。','The ceiling is transparent from above. Choose “Look up at the ceiling” to see its finish.'],['天井の木目を表示しています。上からの全景では透過表示に切り替わります。','The ceiling finish is visible from inside and transparent from above.'],
['カラーパネルなし','No panels'],['カラーパネルあり','Add panels'],['カラーパネル付き（壁に付属）','Panels included with walls'],['壁付きでは、スライドドアとバックドアの2枚が壁と同じ色で付きます。リアサイドは壁仕上げになります。','With walls selected, matching panels cover the sliding door and tailgate. The rear side uses the wall finish.'],['壁を付けずに、窓下3枚のパネルだけを選ぶこともできます。','You can add the three window panels without adding walls.'],['スライドドア＋バックドア・溝なし','Sliding door + tailgate · smooth panels'],['窓下3枚・溝なし','Three smooth panels below the windows'],['カラーパネル3枚を見る','View all three panels'],['カラーパネルを見る','View the panels'],['パネルを見る','View panels'],['バックドアを見る','View the tailgate'],
['床仕上げなし','No floor finish'],['床仕上げあり','Add floor finish'],['床とステップは透過表示','Floor and steps stay transparent'],['選んだ床柄＋黒い樹脂ステップ','Selected flooring + black resin step'],['床の柄','Floor finish'],['床を選ぶと、スライドドアのステップも黒い樹脂仕上げになります。','Adding flooring also adds the black resin sliding-door step.'],['床・ステップを見る','View floor and step'],['ホワイトアッシュ','White ash'],['ウォールナット','Walnut'],['ブラックチェリー','Black cherry'],['ダークキャンバス','Dark canvas'],['ライトキャンバス','Light canvas'],['オーク','Oak'],['チーク','Teak'],['ホワイト','White'],['ブラック','Black'],['天然木突板','Real wood veneer'],['突板天井','veneer ceiling'],['の天井',' ceiling'],['の壁面',' walls'],['ホワイト壁面','White wall'],['テフィ壁面','Teffy wall'],['ボルカニックグレー壁面','Volcanic gray wall'],['キャンバス床','canvas floor'],['ウォールナット床','Walnut flooring'],['チーク床','Teak flooring'],['オーク床','Oak flooring'],['ダークキャンバス床','Dark canvas flooring'],['ライトキャンバス床','Light canvas flooring'],['の合板見本',' plywood sample'],['の壁面＋',' walls + '],['・天然木突板',' · real wood veneer'],
['天井ダウンライト','Ceiling downlights'],['バックドアライト','Tailgate lights'],['6灯 · 電球色3200K','6 lights · warm white 3200K'],['2灯 · 電球色3200K','2 lights · warm white 3200K'],['シルバー仕上げ・電球色3200K。天井ライトには天井、バックドアライトにはパネルが付きます。','Silver finish, warm white 3200K. Ceiling lights include a ceiling; tailgate lights include panels.'],['追加する','Add'],['選択中','Selected'],['照明の追加','Add lighting'],['☾ ナイトモード','☾ Night mode'],['☀ 昼の表示に戻す','☀ Day mode'],['車内の明かりを見る','View cabin lighting'],['バックドアの明かりを見る','View tailgate lighting'],['昼の表示 · ライトを選んでナイトモードへ','Day view · select lights, then try night mode'],['照明を追加すると、照らされ方を確認できます。','Add lights to preview the lighting.'],['点灯時の雰囲気を確認するイメージです。','A preview of the lighting atmosphere.'],['灯を点灯しています · 電球色3200K',' lights on · warm white 3200K'],['灯 · 点灯イメージ',' lights · preview'],['NIGHT / 消灯','NIGHT / lights off'],['灯',' lights'],
['エアコンなし','No air conditioner'],['エアコンの選択','Choose air conditioning'],['CUBE AIR460B ブラックの室内機','CUBE AIR460B black indoor unit'],['室内機＋右側配管カバー','Indoor unit + right-hand pipe cover'],['エアコンを選ぶと壁も付きます。壁を外すとエアコンも外れます。','Selecting air conditioning adds walls. Removing the walls also removes the air conditioner.'],['エアコンを選ぶと、壁仕上げも自動で追加されます。','Selecting air conditioning automatically adds a wall finish.'],['選択中の壁仕上げにエアコンを追加できます。','Add air conditioning to your selected wall finish.'],['の壁に設置しています。',' wall finish selected.'],['エアコンを近くで見る','View the air conditioner'],['（配管カバー付き）',' (with pipe cover)'],
['展開・収納','Extend & store'],['前側のベッド','Front bed section'],['後側のベッド','Rear bed section'],['ベッドを横へ広げる','Extend the bed sideways'],['中央マットレスを敷く','Lay the centre cushions'],['中央の板を後ろへ（オプション）','Slide the centre board rearward (optional)'],['後部収納を引き出す','Pull out rear storage'],['開く','Open'],['閉じる','Close'],['横へのスライド量 ','Sideways extension: '],['車体と家具の位置に合わせて、横への展開を','The vehicle and furniture limit this extension to '],['mmに抑えた表示です。単体の表示上の最大量は',' mm. The standalone preview allows up to '],['mmです。',' mm.'],['シートを残すため、ベッドの前側セルを1800mm仕様に調整した配置です。','The front bed section is adjusted to 1,800 mm to keep the second-row seat.'],
['この組み合わせで。','Your layout.'],['選んだ家具と仕上げを確認できます。','Review your furniture and finishes.'],['前側','Front'],['仕上げ','Finish'],['照明','Lighting'],['サイド','Side'],['ベッド長 ','Bed length: '],['横への展開 ','Sideways extension: '],['ナロー車体 · ','Narrow body · '],['合板',' plywood'],['なし','None'],['配置の確認事項があります','Fit adjustments to review'],['配置の確認事項あり','Fit adjustments need review'],['配置の確認事項','Fit notes'],['配置について','About the fit'],['配置の確認ができた構成','Layout checked against the reference model'],['車体合わせの確認箇所があります','Some areas require fit adjustments'],['確認位置の印を隠す','Hide fit markers'],['確認位置を車体に表示','Show fit markers'],['ナロー参照車体による配置イメージです。製作時は実車採寸・可動範囲・取付方法を確認します。','A layout preview using the reference narrow-body van. Actual measurements, movement and mounting need checking before production.'],['組み合わせを保存','Save configuration'],['画像を保存 ↗','Save image ↗'],['選んだ組み合わせを保存しました。','Configuration saved.'],['この角度の画像を保存しました。','Image saved.'],['各モジュールを詳しく見る ↗','Module details (Japanese) ↗'],
['後ろ','Rear'],['真上','Top'],['車内','Inside'],['見る角度','View angle'],['最初の角度に戻す','Reset view'],['ホームの角度に戻す','Home view'],['ドラッグで回転','Drag to rotate'],['· スクロールで拡大','· Scroll to zoom'],['車体は透過表示','Transparent vehicle shell'],
['家具、内装、設備。好きな組み合わせを選ぶと、その場で3Dに反映されます。','Furniture, finishes, equipment. Make your choices and see them together in 3D.'],['選ぶ','Choose'],['見る','Explore'],['残す','Save'],['4つのタブから、付けたいものを選択。','Use the four tabs to choose what goes inside.'],['3Dをドラッグして回転。「展開・収納」で使うときの動きも確認。','Drag to rotate the 3D view. Use “Extend & store” to preview movement.'],['「確認」から、組み合わせや画像を保存。','Open “Review” to save a configuration or image.'],['写真はHexaの実車イメージです。','Photo: a real Hexa interior.'],['スタジオで選ぶ →','Start configuring →'],['Hexaの実車内装。後部へ引き出せるユーロコンテナとベッド','A Hexa van interior with a bed and rear pull-out Eurocontainers'],
['壁','Walls'],['天井','Ceiling'],['床','Floor'],['夜','Night'],['昼','Day'],['ハイエース3D','Hiace 3D'],
['タイヤハウス・内張りと家具の逃げを確認します。','Check furniture clearance around wheel arches and interior trim.'],['前後の家具が重なるため、現寸法のままでは収まりません。寸法や配置の調整が必要です。','Front and rear furniture overlap at the current dimensions. The size or position needs adjustment.'],['開いた状態にも確認箇所があります。','Open positions also have areas to check.'],['ベッド前側の長さを調整した配置案です。','This preview adjusts the front bed section length.'],['閉じた配置で、追加した壁板とベッドの端に重なりがあります。壁板の厚みに合わせた取り合いの調整が必要です。','The bed edge overlaps the added wall boards in the closed position. Allow for wall thickness when adjusting the fit.'],['参照形状の範囲では、閉じた状態と確認した展開位置で重なりを検出していません。','No intersections were detected in the reference geometry at the closed and checked open positions.'],['現状の単体形状を保持しています。','The current standalone geometry is retained.']
];
pairs.push(['フロントモジュール（プライウッド）','Front module (Plywood)'],['フロントモジュール（アルミ）','Front module (Aluminium)'],['35L冷蔵庫・シンク・シャワー・スツール','35 L fridge · Sink · Shower · Stool'],['35L冷蔵庫・シンク・シャワー','35 L fridge · Sink · Shower']);
pairs.push(['家具をタップ・クリックで詳細','Tap or click furniture for details']);
pairs.push(
['TEFFY壁面','Teffy wall'],['ホワイトアッシュの突板天井','White ash veneer ceiling'],['ウォールナットの突板天井','Walnut veneer ceiling'],['ブラックチェリーの突板天井','Black cherry veneer ceiling'],
['1800mmベッドの基準前端と冷蔵庫横の壁面を合わせて配置。','Aligned to the 1,800 mm bed front and the wall beside the fridge.'],
['55mm前方の位置を保ち、背面側を助手席側へ8.5mm移動。','Retains the 55 mm forward position; the rear face moves 8.5 mm toward the passenger-side wall.'],
['スツールの幅を保ち、ベッド側の箱と天板を130mm後方へ延長してベッド前端に合わせています。','The stool width is retained. The box and worktop extend 130 mm rearward to meet the bed front.'],
['スツールの幅を保ち、ベッド側の箱と天板を140mm後方へ延長してベッド前端に合わせています。','The stool width is retained. The box and worktop extend 140 mm rearward to meet the bed front.'],
['ベッド前端の逃げを確保して20mm前方に配置。','Positioned 20 mm forward for clearance at the bed front.'],
['収納口が室内を向くよう180度回転し、背面側を助手席側へ10mm移動。','Rotated 180° so storage opens into the cabin, with the rear face moved 10 mm toward the passenger side.'],
['天板を運転席側の壁に合わせて68.6mm外側へ配置。','Positioned 68.6 mm outward to align the bed top with the driver-side wall.'],
['後端の逃げを保ち、天板を運転席側の壁に寄せて配置。','Retains rear clearance and aligns the bed top with the driver-side wall.'],
['背面側を助手席側の元の壁面に合わせて8.3mm外側へ配置。','Rear face moved 8.3 mm outward to the original passenger-side wall.'],
['背面側を助手席側の元の壁面に合わせて8.4mm外側へ配置。','Rear face moved 8.4 mm outward to the original passenger-side wall.']
);
pairs.push(...[["シンプルスライドアウトベッド（プライウッド）", "Simple slide-out bed (Plywood)"], ["収納付きスライドアウトベッド（プライウッド）", "Slide-out bed with storage (Plywood)"], ["スライドアウトベッド（アルミ）", "Slide-out bed (Aluminium)"], ["ラウンジベッド（プライウッド）", "Lounge bed (Plywood)"], ["床スライド付きラウンジベッド（プライウッド）", "Lounge bed with floor slide (Plywood)"], ["シンプルなスライドアウト式ベッド", "A simple slide-out bed"], ["工具を収納できる後部引き出し・室内側の収納", "Rear drawer for tools · Storage accessible from inside"], ["前後2分割のスライドアウト・後部の引き出し式ユーロコンテナ収納", "Independent front and rear slides · Rear pull-out Eurocontainer storage"], ["後部に大きな収納を持つラウンジ型ベッド", "A lounge bed with generous rear storage"], ["通路にスライドアウト式の引き出しを設置可能（オプション）", "An optional slide-out drawer can be fitted in the aisle"]]);
pairs.push(...[["シンプルスライドアウトベッド", "Simple slide-out bed"], ["収納付きスライドアウトベッド", "Slide-out bed with storage"], ["床スライド付きラウンジベッド", "Lounge bed with floor slide"], ["ラウンジベッド", "Lounge bed"], ["（プライウッド）", " (Plywood)"], ["（アルミ）", " (Aluminium)"]]);
pairs.push(...[["フリップアップテーブル付きサイドキャビネット", "Side cabinet with flip-up table"], ["シンク付きサイドキャビネット", "Side cabinet with sink"], ["サイドキャビネット", "Side cabinet"], ["冷蔵庫付きサイドキャビネット", "Side cabinet with fridge"]]);
pairs.push(['仕上げなし','No finish'],['未選択','Not selected'],['天然木突板天井','Real wood veneer ceiling'],['壁面パネル','Wall panels'],['オプション','Optional'],['壁面パネルには、同色のカラーパネルも付きます。','Wall panels include matching colour panels.'],['窓下3枚のパネルだけを取り付けます。','Add the three smooth panels below the windows.']);
pairs.push(['内装から、選んでみましょう。','Start with your interior finishes.'],['内装、家具、装備。好きな組み合わせを選ぶと、その場で3Dに反映されます。','Finishes, furniture, equipment. Make your choices and see them together in 3D.'],['家具へ →','Furniture →'],['装備へ →','Equipment →'],['装備','Equipment']);
pairs.push(['ベバスト FFヒーター','Webasto heater'],['FFヒーターの選択','Heater selection'],['FFヒーター','Heater'],['ヒーターなし','No heater'],['ヒーター選択中','Heater selected']);
pairs.push(['断熱施工の選択','Insulation selection'],['断熱施工なし','No insulation'],['断熱施工選択中','Insulation selected'],['車内の断熱施工写真','Interior insulation installation'],['断熱施工','Insulation'],['選択中','Selected']);
pairs.push(['内装、家具、装備、電装。好きな組み合わせを選ぶと、その場で3Dに反映されます。','Finishes, furniture, equipment and power. Make your choices and see them together in 3D.'],['各タブから、付けたいものを選択。','Use the tabs to choose what goes inside.'],['電装へ →','Power →'],['電装パッケージ内容','Electrical package contents'],['電装パッケージ','Power package'],['電装','Power'],['バッテリーシステム','Battery system'],['スタンダードパッケージ','Standard package'],['充電器とサブバッテリーをセットで。','Chargers and a leisure battery in one package.'],['走行充電器','DC–DC charger'],['外部充電器','Mains charger'],['リチウムイオンバッテリー','Lithium-ion battery'],['サブバッテリー容量','Leisure battery capacity'],['サブバッテリー','Leisure battery'],['アップグレード','Upgrade'],['標準','Standard'],['インバーター出力','Inverter output'],['エアコンを選択される場合は、300Ahのバッテリーをおすすめします。','A 300Ah battery is recommended when choosing air conditioning.'],['走行40A · 外部40A','DC–DC 40A · Mains 40A'],['走行充電40A','DC–DC charger 40A'],['外部充電40A','Mains charger 40A'],['リチウムイオン','Lithium-ion '],['バッテリー','Battery '],['インバーター','Inverter ']);
pairs.push(['神奈川県','Kanagawa'],['ブリスベン','Brisbane'],['神奈川とブリスベン、2つの拠点から。','Two bases. Kanagawa & Brisbane.'],['ロケーション','Location'],['神奈川県 / 日本','Kanagawa / Japan'],['ブリスベン / オーストラリア','Brisbane / Australia']);
pairs.push(['Shippingへ →','Shipping →'],['必要なサポートを選択してください。両方選ぶこともできます。','Choose the support you would like. You can select both options.'],['車両ソーシング・オークション代行','Vehicle sourcing & auction agent'],['日本での車両探し・オークション仕入れの代行を希望する。','I would like an agent to source a vehicle in Japan and assist with auction purchases.'],['輸送・登録の手配','Shipping & registration agent'],['完成後の車両輸送から、オーストラリアでの登録までの手配を希望する。','I would like an agent to arrange shipping of the completed vehicle and registration in Australia.'],['車両調達','Vehicle sourcing'],['輸送・登録','Shipping & registration'],['代行を希望する','Agent requested'],['手配を希望する','Assistance requested'],['希望しない','Not requested']);
pairs.push(['車両調達エージェントの紹介','Vehicle sourcing agent referral'],['日本での車両探し・オークション代行を行う外部エージェントの紹介を希望する。','I would like an introduction to an external agent for vehicle sourcing and auction purchases in Japan.'],['輸送・登録エージェントの紹介','Shipping & registration agent referral'],['完成後の輸送・オーストラリアでの登録を手配する外部エージェントの紹介を希望する。','I would like an introduction to an external agent for shipping the completed vehicle and arranging registration in Australia.'],['当社は外部エージェントの紹介を行います。車両調達・オークション代行・輸送・登録の手配は、紹介先のエージェントが対応します。','We provide introductions to external agents. Vehicle sourcing, auction purchases, shipping and registration are handled by the agent, not by us.'],['外部エージェントの紹介を希望','External agent referral requested'],['外部エージェントへの紹介希望です。各手配は紹介先のエージェントが行います。','This is a request for an external agent referral. All arrangements are handled by the agent.']);
pairs.push(['希望車両情報','Vehicle preferences'],['希望の燃料','Preferred fuel'],['希望の駆動方式','Preferred drivetrain'],['燃料','Fuel'],['駆動方式','Drivetrain'],['ガソリン','Petrol'],['ディーゼル','Diesel'],['車両本体の予算','Vehicle-only budget'],['車両本体にかける予算です（オーストラリアドル）。','Budget for the vehicle itself, in Australian dollars.']);
pairs.push(['登録する州・配送先','Registration & destination'],['登録する州・準州','Registration state / territory'],['州・準州を選択','Select a state / territory'],['郵便番号','Postcode'],['エリア（Suburb / Town）','Suburb / Town'],['エリアを選択','Select a suburb / town'],['例：4000','e.g. 4000'],['4桁の郵便番号を入力すると、エリアの候補が表示されます。','Enter a four-digit postcode to see matching suburbs and towns.'],['郵便番号を4桁で入力してください。','Enter all four digits of the postcode.'],['エリアを確認しています…','Looking up the area…'],['エリア情報を読み込めませんでした。再試行できます。','The area data could not load. Please try again.'],['該当するエリアが見つかりません。郵便番号を確認してください。','No matching area was found. Please check the postcode.'],['この郵便番号には複数の州・準州のエリアがあります。登録する州を選択してください。','This postcode covers more than one state or territory. Please choose your registration state.'],['郵便番号のエリアと登録する州が一致していません。州または郵便番号を確認してください。','The postcode does not match the registration state. Please check the state or postcode.'],['該当するエリアを選択してください。','Select the matching suburb or town.'],['配送先のエリア','Destination area'],['未入力','Not entered'],['要確認','Please check'],['再試行','Try again'],['郵便番号データ：','Postcode data: ']);
pairs.push(['トヨタ ハイエース バン DX','Toyota HiAce 200 Series DX'],['標準ボディ（ナロー）・標準ルーフ・5ドア専用','LWB · Narrow body · Standard roof · 5-door only'],['対応車種','Compatible vehicle']);
pairs.push(...[["家具・内装のモジュールおよびパーツのメーカー、Hexaの公式スタジオです。", "The official studio of Hexa, a manufacturer of modular furniture and interior parts."], ["表示額は、家具モジュール（組み立て済み）と内装パーツのメーカー参考販売価格です。車両への取付・施工費は含みません。実際の販売価格は各取扱店が決定し、正式なお見積もりをご案内します。", "The manufacturer reference retail price covers assembled furniture modules and interior parts. Fitting and installation into the vehicle are excluded. Each dealer sets its final selling price and provides a formal quote."], ["この仕様で取扱店に見積もりを依頼する", "Request a dealer quote for this layout"], ["完成車を確認して、見積もり依頼へ →", "View your van and continue to a quote request →"], ["正式なお見積もりは、車両・施工内容の確認後に取扱店からご案内します。", "A dealer will provide your formal quote after reviewing the vehicle and installation requirements."], ["見積もり依頼を閉じる", "Close quote request"], ["取扱店への見積もり依頼", "Request a dealer quote"], ["選んだ仕様を添えて、取扱店への見積もり依頼を準備します。", "Prepare a dealer quote request with your chosen configuration."], ["お住まいの地域（都道府県・州）", "Your region / state"], ["ご希望・ご質問（任意）", "Requests or questions (optional)"], ["現在は見積もり依頼の下書きを保存できます。取扱店へはまだ送信されません。", "For now, you can save a quote request draft. It will not be sent to a dealer yet."], ["見積もり依頼の下書きを保存", "Save quote request draft"], ["見積もり依頼の下書きを保存しました。取扱店へはまだ送信されていません。", "Quote request draft saved. It has not been sent to a dealer."], ["見積もり依頼をコピーしました。取扱店へはまだ送信されていません。", "Quote request copied. It has not been sent to a dealer."], ["コピーできませんでした。「見積もり依頼の下書きを保存」をお使いください。", "Could not copy. Please use “Save quote request draft”."]]);
pairs.push(...[["電話番号", "Phone number"], ["郵便番号", "Postcode"], ["例：123-4567", "e.g. 123-4567"], ["7桁でご入力ください。ハイフンはあってもなくても大丈夫です。住所の入力は不要です。", "Enter the seven-digit Japanese postcode, with or without a hyphen. No street address is needed."], ["お名前・メールアドレス・電話番号・郵便番号は必須です。", "Name, email address, phone number and postcode are required."], ["お名前・メールアドレスは必須です。", "Name and email address are required."]]);
pairs.push(...[["7桁でご入力ください。分かる範囲の住所を自動表示します。", "Enter seven digits to automatically show the available address."], ["郵便番号から分かる住所", "Address from your postcode"], ["該当する町域（任意）", "Your area (optional)"], ["住所データ：日本郵便", "Address data: Japan Post"], ["再読み込み", "Retry"], ["郵便番号から住所を確認しています…", "Looking up the address…"], ["住所を読み込めませんでした。再読み込みするか、郵便番号のみで下書きを保存できます。", "The address could not be loaded. Retry or save the draft with just your postcode."], ["該当する住所が見つかりません。郵便番号をご確認ください。郵便番号のみでも下書きを保存できます。", "No address was found. Please check your postcode. You can still save the draft with just the postcode."], ["複数の町域があります。該当する町域を選べます。", "This postcode covers several areas. You can select your area."], ["この郵便番号では市区町村まで表示します。", "This postcode identifies the municipality only."], ["番地・建物名の入力は不要です。", "No street number or building name is needed."]]);
pairs.push(...[["車両のご用意（必須）", "Base vehicle (required)"], ["新車の手配から依頼する", "Arrange a new vehicle"], ["新車をベースに内装を製作", "Build the interior in a new van"], ["車両を持ち込む", "Bring my own vehicle"], ["お持ちの車両をベースに内装を製作", "Build the interior in your existing van"], ["車両のご用意・お名前・メールアドレス・電話番号・郵便番号は必須です。", "Please choose your vehicle option and enter your name, email address, phone number and postcode."]]);
pairs.push(...[["新車の仕様", "New vehicle preferences"], ["燃料（必須）", "Fuel (required)"], ["ガソリン", "Petrol"], ["ディーゼル", "Diesel"], ["駆動方式（必須）", "Drivetrain (required)"], ["2WD（二輪駆動）", "2WD"], ["4WD（四輪駆動）", "4WD"], ["燃料を選ぶと、駆動方式を選べます。", "Choose a fuel type to see the drivetrain options."], ["ガソリン車は2WDのみです。", "Petrol vehicles are available in 2WD only."], ["ディーゼル車は2WD・4WDから選べます。", "Diesel vehicles can be configured with 2WD or 4WD."]]);
pairs.push(...[["床は必須です。柄を選ぶと次へ進めます。", "Flooring is required. Choose a finish to continue."], ["床を選ぶ", "Choose flooring"], ["最小構成は床のみ。家具やその他の内装・装備は必要に応じて追加できます。", "Start with flooring only. Furniture, other finishes and equipment are optional."], ["必須", "Required"]]);
pairs.push(['床スライド','Floor slide'],['脱着式・追加あり','Removable · added'],['追加なし','Not added']);
pairs.push(...vehicleTranslations);
// Explain the manufacturer, studio and dealer roles in either language.
pairs.push(...[["モジュール・パーツメーカー Hexa", "Hexa · modules & parts manufacturer"], ["Hexaは家具・内装のモジュールとパーツを設計・製作・販売しています。このスタジオで組み合わせを確認し、取扱店にご相談いただけます。", "Hexa designs, manufactures and supplies furniture modules and interior parts. Use this studio to explore combinations and discuss your layout with a dealer."], ["正式なお見積もりと販売は取扱店、車両への取付・施工は施工店が担当します。", "Dealers handle sales and formal quotes. Installers fit the modules and parts to your vehicle."]]);
pairs.push(['天井ライト用開口','Ceiling light cutouts'],['バックドアライト用開口','Tailgate light cutouts'],['バックドアライト（取付希望）','Tailgate lights (fitting request)']);
pairs.push(['車体へ →','Vehicle →'],['車体','Vehicle']);
pairs.push(['架装パーツ参考価格は、家具モジュール（組み立て済み）と内装パーツの価格です。新車込みの場合は、合計に新車参考価格も含みます。取付・施工費は別途です。正式なお見積もりは取扱店よりご案内します。', 'The fit-out reference price covers assembled furniture modules and interior parts. When a new vehicle is selected, the total includes its reference price. Fitting and installation are extra. Your dealer will provide a formal quote.']);
const dict=new Map(pairs),ordered=[...dict].sort((a,b)=>b[0].length-a[0].length);
const LOCATIONS={jp:{id:'jp',country:'Japan',base:'Kanagawa',label:'神奈川県 / 日本',language:'ja'},au:{id:'au',country:'Australia',base:'Brisbane',label:'ブリスベン / オーストラリア',language:'en'}};
const preferenceKey='hexa-studio-locale';
function readLocale(){
 const q=new URLSearchParams(location.search);let saved={};
 try{saved=JSON.parse(localStorage.getItem(preferenceKey))||{}}catch{}
 const explicitLocation=Object.hasOwn(LOCATIONS,q.get('location'));
 const requested=explicitLocation?q.get('location'):Object.hasOwn(LOCATIONS,saved.location)?saved.location:'jp';
 const place=resolveDealerLocation(requested);
 const lang=['ja','en'].includes(q.get('lang'))?q.get('lang'):(explicitLocation||place!==requested)?LOCATIONS[place].language:['ja','en'].includes(saved.language)?saved.language:LOCATIONS[place].language;
 return {place,lang};
}
let {place:selectedLocation,lang:language}=readLocale();
export const getStudioLocation=()=>{const {id,country,base,label}=LOCATIONS[selectedLocation];return {id,country,base,label}};
const originals=new WeakMap(),attributes=new WeakMap();let observer,pending=false;
export const getLanguage=()=>language;
export function translate(text){
 const trimmed=text.trim();if(dict.has(trimmed))return text.replace(trimmed,dict.get(trimmed));
 let value=text;for(const [from,to] of ordered)value=value.split(from).join(to);return value;
}
function updateValue(node,key,current,cache){
 let entry=cache.get(key);if(!entry||current!==entry.last)entry={source:current,last:current};
 const next=language==='en'?translate(entry.source):entry.source;
 if(next!==current){if(key==='text')node.nodeValue=next;else node.setAttribute(key,next)}entry.last=next;cache.set(key,entry);
}
function renderLanguage(){
 observer?.disconnect();document.documentElement.lang=language;
 const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);let node;
 while(node=walker.nextNode()){
  if(node.parentElement?.closest('script,style,[data-lang],[data-module-i18n]'))continue;
  let cache=originals.get(node);if(!cache){cache=new Map();originals.set(node,cache)}updateValue(node,'text',node.nodeValue,cache);
 }
 for(const el of document.querySelectorAll('[aria-label],[title],[alt],[placeholder]')){
  if(el.closest('[data-module-i18n],[data-lang]'))continue;
  let cache=attributes.get(el);if(!cache){cache=new Map();attributes.set(el,cache)}
  for(const key of ['aria-label','title','alt','placeholder'])if(el.hasAttribute(key))updateValue(el,key,el.getAttribute(key),cache);
 }
 document.querySelectorAll('[data-lang]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.lang===language));
 document.querySelectorAll('[data-location]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.location===selectedLocation));
 observer?.observe(document.body,{subtree:true,childList:true,characterData:true,attributes:true,attributeFilter:['aria-label','title','alt','placeholder']});
}
function schedule(){if(pending)return;pending=true;queueMicrotask(()=>{pending=false;renderLanguage()})}
function commitLocale(){
 selectedLocation=resolveDealerLocation(selectedLocation);
 const url=new URL(location.href);
 url.searchParams.set('location',selectedLocation);
 // An explicit language also preserves Australia + Japanese in shared links.
 url.searchParams.set('lang',language);
 history.replaceState(null,'',url);
 try{localStorage.setItem(preferenceKey,JSON.stringify({location:selectedLocation,language}))}catch{}
 renderLanguage();
 window.dispatchEvent(new CustomEvent('studio-locale-change',{detail:{location:selectedLocation,language}}));
}
export function initLanguage(){
 observer=new MutationObserver(schedule);
 document.querySelectorAll('[data-lang]').forEach(b=>b.addEventListener('click',()=>{
  language=b.dataset.lang;commitLocale();
 }));
 document.querySelectorAll('[data-location]').forEach(b=>b.addEventListener('click',()=>{
  if(resolveDealerLocation(b.dataset.location)!==b.dataset.location)return;
  selectedLocation=b.dataset.location;language=LOCATIONS[selectedLocation].language;commitLocale();
 }));
 window.addEventListener('popstate',()=>{
  ({place:selectedLocation,lang:language}=readLocale());commitLocale();
 });
 commitLocale();
}

